#!/usr/bin/env bash

# Uninstall old version(s)

rm -rf ~/Library/Application\ Support/SIMBL/Plugins/XcodeColors.bundle 2>/dev/null
rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin 2>/dev/null

# Install new version


mkdir -p ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins 2>/dev/null
cp -r ${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME} ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin

echo Installed
